Ignore non-running instances
There are several states in which an EC2 instance can be:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html

In some of those states an instance lacks attributes which are required by
Clusterman (like `SubnetId`).  As a result, Clusterman crashes for such
instances:
```
Traceback (most recent call last):
  File "/code/clusterman/batch/autoscaler.py", line 42, in wrapper
    fn(self)
  File "/code/clusterman/batch/autoscaler.py", line 104, in _autoscale
    self.autoscaler.run(dry_run=self.options.dry_run)
  File "/code/clusterman/autoscaler/autoscaler.py", line 87, in run
    self.mesos_pool_manager.modify_target_capacity(new_target_capacity, dry_run=dry_run)
  File "/code/clusterman/mesos/mesos_pool_manager.py", line 153, in modify_target_capacity
    self.prune_excess_fulfilled_capacity(new_target_capacity, res_group_targets, dry_run)
  File "/code/clusterman/mesos/mesos_pool_manager.py", line 332, in prune_excess_fulfilled_capacity
    marked_instance_ids = self.choose_instances_to_prune(new_target_capacity, group_targets)
  File "/code/clusterman/mesos/mesos_pool_manager.py", line 264, in choose_instances_to_prune
    remaining_non_orphan_capacity = self.non_orphan_fulfilled_capacity
  File "/code/clusterman/mesos/mesos_pool_manager.py", line 465, in non_orphan_fulfilled_capacity
    i.resource_group.market_weight(i.market) for i in self.get_instances() if i.state != MesosAgentState.ORPHANED
  File "/code/clusterman/mesos/mesos_pool_manager.py", line 465, in <genexpr>
    i.resource_group.market_weight(i.market) for i in self.get_instances() if i.state != MesosAgentState.ORPHANED
  File "/code/clusterman/mesos/spot_fleet_resource_group.py", line 49, in market_weight
    return self._market_weights[market]
KeyError: <c5.4xlarge, None>
```

It seems that Clusterman is actually interested only in instances in
`running` state and instances in other states can be safely ignored.